### ISSUE TITLE
Use Cases Beyond Attribution

### ISSUE THREAD

**Issue by tswenson21** [WICG/ad-click-attribution#12]
HI-

We spoke about this when ITP first came out but given you're working out privacy compliant approaches to measurement with the Attribution Use case, what about other types of measurement.    For example, panel based Brand Lift measurement - where the panel is fully opted in to tracking and in fact compensated for the surveys they take.   There has to be a way to work together on a privacy safe approach.

Thoughts?

**Comment by johnwilander** [comment]
We are interested in privacy preserving solutions for other types of measurement too. But this draft spec tackles ad click attribution.

It's also not clear to me what "fully opted in" means at web scale. I consider myself an online privacy professional and I'm not sure I could grasp the implications of "fully opting in to tracking."

**Comment by tswenson21** [comment]
HI thanks for the comment back.  And fair enough  on fully opted in.  Let me explain and see if it makes any more sense.   We operate a global panel of participants who join the panel to take surveys in exchange for rewards points.  People are invited to the panel through their membership in loyalty programs like airline miles, hotel miles, big box retail etc.   Those loyalty programs in turn provide the rewards points for the surveys.    When they join they are asked to agree to a privacy policy which outlines in it the kind of tracking that we do.  They can choose to opt out of that tracking, in which case they are panelists, still get surveys, just not of the Brand Lift measurement type.   For those that agree, when they are invited to a survey we drop a cookie on their browser.   Then when we measure a client advertising campaign, we traffic our measurement tag with the campaign.  When the ad serves our tag loads and tries to read if our cookie is present.  If it is, that is an opted-in panelist and mark them as exposed to the campaign.  We create a control group, run survey, etc.     The only people we capture the information on is our panelists, who are compensated in the form of rewards points.  And we consider those panelists having opted in to and compensated for, the measurement.   In GDPR and Express Consent countries we go even further for certain use cases and ask for additional consent.     So as you can see- once ITP came out, our panelists (who agreed to and are compensated for) the measurement we do can no longer participate if they use Safari as their browser.     How does this fit with your view of things, and is there a form of this that we could consider in a similar way you are creating a new way for the attribution providers.

**Comment by jasonanovak** [comment]
Thanks for clarifying the use case.  The focus of this specification is privacy preserving ad click attribution.  We appreciate that there are other advertising practices out there that this specification does not support.  We would suggest taking your use case to the [W3C Improve Web Advertising Business Group](https://www.w3.org/community/web-adv/) to see if they are interested in helping you incubate a privacy preserving method for panel measurement and brand lift.

I will close the issue but please re-open if there’s a PPACA angle to panel measurement that I’m missing.
