### ISSUE TITLE
Duration of tracking tag

### ISSUE THREAD

**Issue by kengjoran** [WICG/ad-click-attribution#14]
Hi guys,

Thank you for a very detailed summary of Webkit's intentions. It's obviously a huge change from the status quo and a massive change to the foundations of how digital advertising works today.  Which is a combination of scary and exciting to us, being an analytics solution focused on optimising program and campaign performance!

I would like to ask for the reasoning behind the 7 day window for attribution on your ad click tracking. In the performance industry (think affiliate / lead generation etc), the established norm for years have been 30 days attribution.

With the restrictions proposed already being game changing, I would argue keeping non-privacy settings related parameters as close to the norm as possible as long as it keeps users looking similar and you have the delayed reporting. Whilst the majority of transactions/conversions takes place in the 7 day window, the longer window is particularly relevant higher value products and a shortened tracking window will likely impact smaller publishers/websites disproportionately in terms of revenue.

I'm not really able to see the entropy argument on the 30 day window, and I think this is further emphasised by a exponential drop in value of data over time for use in identifying users cross site. If I can contribute from the performance marketing POV in any other way, don't hesitate to let me know. 

Kind regards,
Ken

**Comment by johnwilander** [comment]
> Hi guys,

Hi Ken! Thanks for filing.

> Thank you for a very detailed summary of Webkit's intentions. It's obviously a huge change from the status quo and a massive change to the foundations of how digital advertising works today. Which is a combination of scary and exciting to us, being an analytics solution focused on optimising program and campaign performance!
> 
> I would like to ask for the reasoning behind the 7 day window for attribution on your ad click tracking. In the performance industry (think affiliate / lead generation etc), the established norm for years have been 30 days attribution.

We always start this kind of design work by asking ourselves what the user/customer expects. What is a good feature for them? What is something they can understand and would agree to is reasonable?

Your browser remembering that you clicked on something a week ago and facilitating conversion measurement of such clicks is reasonable, we think. But one month?

Think about your own behavior. "Yeah, I clicked an ad for that product this past weekend" is probably something you could find yourself saying. But do you remember what you clicked on mid-May?

That was our thinking and why we landed in one week. You'll see this same 7-day setting in how we cap the expiry of persistent client-side cookies and the so called grandfathering of website data when Safari first enabled ITP.

> With the restrictions proposed already being game changing, I would argue keeping non-privacy settings related parameters as close to the norm as possible as long as it keeps users looking similar and you have the delayed reporting. Whilst the majority of transactions/conversions takes place in the 7 day window, the longer window is particularly relevant higher value products and a shortened tracking window will likely impact smaller publishers/websites disproportionately in terms of revenue.
> 
> I'm not really able to see the entropy argument on the 30 day window, and I think this is further emphasised by a exponential drop in value of data over time for use in identifying users cross site. If I can contribute from the performance marketing POV in any other way, don't hesitate to let me know.

We might be open to discussing an extended expiry of this data once we've settled on a version 1, shipped it on by default, and had a chance to see how it plays out with adoption and potential abuse. And going from 7 to 30 days in a version 2 will be much easier than going from 30 to 7.

**Comment by johnwilander** [comment]
No more comments here in almost two weeks. Closing.
