### ISSUE TITLE
Suggested name change: Private Click Measurement

### ISSUE THREAD

**Issue by othermaciej** [WICG/ad-click-attribution#15]
The  current name (Privacy Preserving Ad Click Attribution) and its acronym (PPACA) are both a mouthful. Also, PPACA is an alternate for the Affordable Care Act (aka Obamacare).

An alternative that gets the idea across while being easier to say: Private Click Measurement (PCM).

**Comment by johnwilander** [comment]
Sure. Hopefully, just changing the name in the draft spec will do and not moving the WICG repo.

**Comment by johnwilander** [comment]
Resolved in https://github.com/WICG/ad-click-attribution/commit/554e80b6c66a080c06b72dbb783be8b2aa1eb50d.
