### ISSUE TITLE
Did this repo go through normal WICG process?

### ISSUE THREAD

**Issue by cwilso** [WICG/ad-click-attribution#3]
This repo wasn't created or transferred by the chairs, and doesn't seem to have followed the process as stated in https://github.com/WICG/admin (propose on Discourse first, get agreement from multiple parties).

**Comment by hober** [comment]
I think so? I thought the process gate for "create or transfer a repo to the WICG org" was that the idea be reasonably fleshed out and have multi-vendor interest. I suppose the latter isn't clear from the Acks section, but there's interest from at least WebKit (the proposers) and Gecko (Steven & Ehsan). There have definitely been other specs which had multi-implementor interest that went directly to the "create a repo under WICG" step.

**Comment by cwilso** [comment]
Sure, we create new repos under WICG all the time; they don't need to start with a transfer.  We do ask that everything go through a thread in Discourse, so we have clearly documented interest from multiple parties, and the co-chairs are the gatekeepers; apparently we had a legacy permissions issue.

Can you point to the expressions of interest?

**Comment by ehsan** [comment]
Yes, Gecko is indeed interested in this specification.  I've filed https://github.com/mozilla/standards-positions/issues/161 in order to obtain a Mozilla standards position on it.

**Comment by johnwilander** [comment]
OK to close, @cwilso?

**Comment by marcoscaceres** [comment]
Having multi-implementer interest is fantastic. However, it would still be nice to post something on Discourse to inform the community. Ideally it would outline the general idea, that Mozilla is collaborating with the WebKit community on it, and areas that you'd like input on from developers (e.g., the WebKit post mentions needing input on the well-known URL, anything else?) and how it might impact them... and a link to the WebKit post would be great.

**Comment by othermaciej** [comment]
We'll gladly make a Discourse post (perhaps tomorrow). We'd really prefer discussion to be in GitHub Issues rather than Discourse. Wo we will likely nudge people in that direction. Hopefully that is ok.

**Comment by marcoscaceres** [comment]
> We will likely nudge people in that direction. Hopefully that is ok.

Yes, that's absolutely fine. I can even close the thread to make sure discussion happens here.

**Comment by darobin** [comment]
Expression of interest ✋ !

**Comment by cwilso** [comment]
Make a post on Discourse, get some people to comment.  Those people clearly exist; we just need to document that.  (Note that this is the bar we apply to everyone before the chairs create or transfer a repo; the only difference is you shouldn't have been able to just create a repo here; our bad, apparently.)

**Comment by othermaciej** [comment]
@cwilso  To be clear, are you saying that  a Discourse post pointing here, plus the people who have already expressed interest here  (@ehsan for Mozilla, @darobin) would be insufficient? You specifically need them to express their support on Discourse? That seems at odds with what @marcoscaceres has said and maybe a bit overly legalistic. Could the WICG chairs please confer and give us a consistent answer on the right thing to do?

(Also, belated apologies for misunderstanding the process rules. WICG has always seemed a bit Wild West to us, but we should have done a better job of determining the correct process.)

**Comment by cwilso** [comment]
I'd like to make sure there's some relatively easily detected evidence, but that doesn't mean that @ehsan or @darobin need to comment on Discourse.  Just comment in that post that there *IS* such support, and go ahead and close this issue when that post has been made.  (I think that's 100% compatible with what Marcos said.)

The reasoning for this is to help prevent dropping single-vendor proposals straight in as "proposed standards" (note that I most assiduously apply this rule to Google proposals).  We want this to be a place where collaboration happens.

In future - just start with a post on Discourse, and it'll all flow from there.

**Comment by hober** [comment]
@cwilso okay! for timezone reasons, I might not get to it for a few hours, but I'll try to do it before I go to bed tonight.

**Comment by hober** [comment]
Okay, I've [recorded](https://discourse.wicg.io/t/privacy-preserving-ad-click-attribution/3582) the multi-vendor interest in this on Discourse as @cwilso requested.

@othermaciej wrote:

> > We'd really prefer discussion to be in GitHub[…] We will likely nudge people in that direction. Hopefully that is ok.

@marcoscaceres replied:

> Yes, that's absolutely fine. I can even close the thread to make sure discussion happens here.

That would be great! Now that the thread is there, please do so when you have the chance.

@cwilso wrote:

> Just comment in that post that there _IS_ such support

Done.

> and go ahead and close this issue when that post has been made.

Okay.

**Comment by hober** [comment]
Oh, never mind, there's a "close topic" option under the wrench menu. Done. @marcoscaceres, you're off the hook. Thanks again!

**Comment by marcoscaceres** [comment]
Thanks everyone! Really looking forward to seeing where this goes. If you need anything from me or any of the chairs, just ping.
