### ISSUE TITLE
Consideration for links in sourceless iframes

### ISSUE THREAD

**Issue by bloodyowl** [WICG/ad-click-attribution#4]
Sourceless iframes (`src="about:blank"` or `srcdoc=""`) can be used:

- to isolate widgets from the website's existing CSS in order to guarantee a similar experience to every user
- to isolate the page from new CSS that might break it

AFAIK it's also used by AMP to provide similar kinds of isolation.

Given they don't have by themselves access to any storage, it'd be nice if links in sourceless iframes were considered to be first-party links and enable them ad click attribute for them.

**Comment by othermaciej** [comment]
Sourceless iframe of that type are considered same-origin with the parent. It probably makes sense to allow this API in same-origin frames,. since they are effectively part of the same page, just a specific way  of constructing it.

**Comment by johnwilander** [comment]
This sounds reasonable to me too.

**Comment by johnwilander** [comment]
This request will be handled by the changes we discuss in https://github.com/WICG/ad-click-attribution/issues/7 so closing this one.
