### ISSUE TITLE
Use camelCase for IDL attributes

### ISSUE THREAD

**Issue by zcorpan** [WICG/ad-click-attribution#5]
```
partial interface HTMLAnchorElement {
    [CEReactions=NotNeeded, Reflect] attribute DOMString adcampaignid;
    [CEReactions=NotNeeded, Reflect] attribute DOMString addestination;
};
```

Per convention in html these should be `adCampaignId` and `adDestination`

**Comment by johnwilander** [comment]
I know I wrote these in lower case for some reason but it was too far back for me to remember. I'll try to dig it up. Maybe it was for stupid implementation reasons and you are totally right.

**Comment by johnwilander** [comment]
Retracing my steps. The `a` element is specified here:
https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element

I remember noting that all existing attributes that unconditionally reflect their values are lower case and the two that don't are camel cased. But it's also the fact that only `hreflang` would be camel cased and the two existing camel cased ones are more recent.

Do you have any insights into this?

**Comment by zcorpan** [comment]
I would assume that `hreflang` casing is a mistake made a long time ago.

https://www.w3.org/TR/2003/REC-DOM-Level-2-HTML-20030109/html.html#ID-48250443
has `hreflang` on `a`, but also `accessKey` and `tabIndex` (which also reflect).

**Comment by othermaciej** [comment]
I believe @zcorpan is correct, the modern practice is to use camelCase for IDL properties that reflect HTML attributes, but some of the very oldest ones are all lowercase instead.

**Comment by johnwilander** [comment]
Resolved in https://github.com/WICG/ad-click-attribution/commit/554e80b6c66a080c06b72dbb783be8b2aa1eb50d.
