### ISSUE TITLE
Privacy-safe mechanism for frequency capping

### ISSUE THREAD

**Issue by darobin** [WICG/ad-click-attribution#8]
I am not certain that this fits well into this specific spec, but John suggested I open an issue and so I am. We can park it and copy it elsewhere when that elsewhere exists.

One important use case for advertising is frequency capping. The fundamental idea is pretty basic: you don't want people to see the same ad too much. There are some subtleties that can be dug into, but that's the headline. This is typically done with (shockingly) cookies and unique personal identifiers.

Evidently there are complications involved in featuring the ability to indicate that a given user has already seen a specific ad `n` times so as not to see it again.

**Comment by jokeyrhyme** [comment]
I guess this would have to be performed client-side? Have markup that defines 64 different adverts, and how to fetch them, and the browser remembers which of those 64 (on that origin) have already been viewed?

**Comment by michael-oneill** [comment]
Yes, each ad has an id so the browser can choose which to show using some privacy preserving (i.e. no cookies!) algorithm e.g. with frequency capping. It can give the user more control over it also.

**Comment by johnwilander** [comment]
If we stick with the restriction that ad click attribution data is only supported in first-party anchor tags, the first-party should be able to leverage this data—the campaign ID and the destination—to cap the number of times it shows the ad to the same user.

The reason why I say "If we stick …" is the discussion in https://github.com/WICG/ad-click-attribution/issues/7.

**Comment by johnwilander** [comment]
Thanks for bringing up this perspective. We don't really have a change proposed here and it seems we're settling on support for third-party anchor elements in https://github.com/WICG/ad-click-attribution/issues/7 so I'm closing this.
